---
# See: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/extra-docs-linting.yml

name: antsibull-docs-lint

on:
  # Run against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
  pull_request:
  # Run once per day to ensure that even if there haven't been commits that we are still testing against latest version
  # of ansible-test for each ansible-base version
  schedule:
    - cron: '0 4 * * *'

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run antsibull-docs collection linter
        run: antsibull-docs lint-collection-docs . --plugin-docs --skip-rstcheck
